on:
  push:
    branches: [main]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout dist
        uses: actions/checkout@v3
        with:
          ref: dist
          path: dist
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build with NPM
        id: build
        run: |
          npm ci
          npm run build
          cp action.yml dist
          echo "::set-output name=version::$(cat package.json | jq -r '.version')"
      - name: Commit
        working-directory: dist
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -f .
          git commit --allow-empty -m "Build ${{ github.run_number }}"
          git tag -f -a -m "v${{ steps.build.outputs.version }}"
          git push
          git push --tags --force
